import type { AbsoluteTopEvaluation } from "./types";
import { businessDate } from "@/lib/time/tz";
export const ABSOLUTE_TOP_STATE_LABEL = { meets: "Cumple", near: "Cerca del mínimo", below: "Bajo el mínimo", insufficient: "Datos insuficientes", unclassified: "Sin clasificar" };
export const ABSOLUTE_TOP_COVERAGE_LABEL = { complete: "Completa", partial: "Parcial", unavailable: "No disponible" };
const percentage = (value: number | null) => value === null ? "N/D" : `${(value * 100).toFixed(2)}%`;
export function buildAbsoluteTopAlertText(row: AbsoluteTopEvaluation): string {
  const share = (key: "search_impression_share" | "search_lost_is_rank" | "search_lost_is_budget") => row.share_bounds[key] === "lt_10_percent" ? "<10%" : row.share_bounds[key] === "gt_90_percent" ? ">90%" : percentage(row[key]);
  const window = row.window_end_hour !== null && row.window_end_hour !== undefined ? `acumulado [00:00, ${String(row.window_end_hour + 1).padStart(2,"0")}:00)` : row.date < businessDate(new Date(row.audit_at), row.source_timezone) ? "día cerrado" : "día en curso; corte horario no disponible";
  const delta = (value: number | null) => value === null ? "N/D" : `${value.toFixed(2)} pp`;
  return ["Google Ads · Absolute Top", `${row.domain_name ?? "Sin clasificar"} · ${row.account_name} (${row.customer_id})`, `Campaña: ${row.campaign_name}`, ...(row.level === "ad_group" ? [`Grupo: ${row.ad_group_name} · peso por impresiones ${percentage(row.group_weight)}`] : []), `Ventana: ${row.window_from ?? row.date} a ${row.window_to ?? row.date} · ${window} (${row.source_timezone}) · ${row.currency}`, `Cobertura: ${ABSOLUTE_TOP_COVERAGE_LABEL[row.coverage]} · auditoría ${row.audit_id} · ${row.audit_at}`, `Absolute Top: ${percentage(row.absolute_top_rate)} · mínimo ${percentage(row.target_rate)} · brecha ${delta(row.gap_pp)}`, `Estado: ${ABSOLUTE_TOP_STATE_LABEL[row.state]} · severidad ${row.severity} · puntuación ${row.severity_score.toFixed(1)}/100`, `Persistencia: ${row.persistence.label} (${row.persistence.consecutive_audits} auditorías) · duración ${row.persistence.hours_since_detection === null ? "N/D" : `${row.persistence.hours_since_detection.toFixed(1)} h`}`, `Primera detección: ${row.persistence.first_detected_at ?? "N/D"} · última: ${row.persistence.last_detected_at ?? "N/D"}`, `Variación: auditoría anterior ${delta(row.comparison.previous.delta_pp)} · ayer comparable ${delta(row.comparison.previous_day.delta_pp)} · 24 h ${delta(row.comparison.last_24h.delta_pp)} · 7 días ${delta(row.comparison.last_7d.delta_pp)}`, `Impresiones: ${row.impressions ?? "N/D"} · costo: ${row.spend ?? "N/D"} ${row.currency} · conversiones de plataforma: ${row.conversions ?? "N/D"}`, `Top de página: ${percentage(row.top_of_page_rate)} · cuota búsqueda: ${share("search_impression_share")} · pérdida ranking: ${share("search_lost_is_rank")} · pérdida presupuesto: ${share("search_lost_is_budget")}`, ...row.diagnostics, "No modifica campañas ni presupuestos. Las tasas ponderadas por impresiones son aproximadas."].join("\n");
}
